/** Final page copy per website-brief.md §3. Change here, log in docs/design-decisions.md. */
export const copy = {
  nav: { brand: "Mutuals", cta: "Join the waitlist" },
  hero: {
    headline: ["A second brain for", "your relationships."],
    sub: "Send it a voice note after you meet someone. It files the person, the context, and the intro you promised. Then it sends you one message a day. No app to open.",
    placeholder: "Email or WhatsApp number",
    button: "Join the waitlist",
    meta: "Private beta · autumn 2026 · Vienna → everywhere",
    reassurance: "We only message you once, when your spot opens. No newsletter, no spam.",
  },
  demo: {
    transcript: "Met Sarah at the Sequoia dinner, she's building autonomous drones, I want to intro her to Ben.",
    receipt: { title: "Saved to Sarah Lin", lines: ["Sequoia dinner · Aug 28", "+ autonomous drones", "+ intro → Ben Roth"] },
    chips: ["Sarah Lin", "Ben Roth"],
    arcLabel: "intro · pending",
    reminder: "Tomorrow 08:30: reminder to make the intro.",
  },
  how: {
    label: "How it works",
    scenes: [
      { n: "01", title: ["You", "talk."], body: "One voice note after you meet someone. That's the whole input." },
      { n: "02", title: ["It", "remembers."], body: "Every note is filed to the right person. Nothing gets lost in a chat history." },
      { n: "03", title: ["It", "connects."], body: "Ask it anything about your network. Every morning, one message about who matters today." },
    ],
    /** Spoken transcript, split into plain runs and the entities Mutuals extracts. */
    transcript: [
      "Met ",
      { entity: "Sarah" },
      " at the ",
      { entity: "Sequoia dinner" },
      ", she's building ",
      { entity: "autonomous drones" },
      ", I want to intro her to ",
      { entity: "Ben" },
      ".",
    ],
    voice: { duration: 7, time: "21:14" },
    record: {
      name: "Sarah Lin",
      role: "Founder, autonomous drones",
      avatar: "/generated/avatars/a03.webp",
      saved: "Saved from your voice note",
      fields: [
        { k: "Met", v: "Sequoia dinner, Aug 28" },
        { k: "Building", v: "Autonomous drones" },
        { k: "Intro", v: "Ben Roth, you promised" },
        { k: "Next", v: "Reminder tomorrow, 08:30" },
      ],
      ghosts: [
        { name: "Markus Hofer", role: "Partner, Speedinvest", avatar: "/generated/avatars/a07.webp" },
        { name: "Anna Weiss", role: "Climate hardware", avatar: "/generated/avatars/a10.webp" },
      ],
    },
    query: "who do I know in private equity in London?",
    hits: [
      { name: "James Whitfield", why: "Mid-market fund in Mayfair, met at Slush", avatar: "/generated/avatars/a05.webp" },
      { name: "Amara Okafor", why: "Ex-Permira, now runs a family office", avatar: "/generated/avatars/a08.webp" },
      { name: "Daniel Levy", why: "Closed a secondaries fund in May", avatar: "/generated/avatars/a02.webp" },
    ],
    channels: "Lives in WhatsApp and Telegram. No app to install.",
  },
  digest: {
    label: "08:30 · every day · that's it",
    header: "Mutuals · Tue Sep 2",
    items: [
      { n: "1", who: "Sarah Lin", why: "you promised an intro to Ben 9 days ago." },
      { n: "2", who: "Markus Hofer", why: "7 weeks quiet, you usually talk monthly." },
      { n: "3", who: "Anna Weiss ↔ Tom Adler", why: "Anna is raising for climate hardware. Tom said in June he's looking at exactly that." },
    ],
  },
  who: {
    title: "Who it's for",
    body: "Built for people whose network is the job: founders, investors, operators. People who meet twenty new people a week and refuse to adopt another tool. It lives in WhatsApp and Telegram, reads only your calendar and contacts, and never sends anything on your behalf.",
    reads: { title: "It reads", items: ["your calendar", "your contacts", "what you tell it"] },
    never: { title: "It never", items: ["sends on your behalf", "scrapes LinkedIn", "keeps a copy after you delete"] },
    privacy: "EU-hosted · reads calendar & contacts only · drafts, never sends · delete everything in one tap",
  },
  ticker: [
    "who do I know in climate hardware?",
    "which investor did I meet at Slush?",
    "who promised me an intro?",
    "who's building in Vienna?",
    "who did I meet at the Sequoia dinner?",
    "who should meet Anna?",
    "who went quiet this month?",
  ],
  network: {
    title: "It connects the dots.",
    query: "who do I know in private equity in London?",
    names: ["Sarah Lin","Ben Roth","James Whitfield","Amara Okafor","Daniel Levy","Anna Weiss","Tom Adler","Markus Hofer","Nadia Aziz","Felix Stern","Clara Huang","Omar Haddad","Julia Novak","Leon Baptiste","Priya Nair","Jonas Wild","Elif Kaya","Max Reiter","Sofia Ortega","Tim Achebe","Hanna Lund","Noah Fischer","Ava Brandt","Kai Nakamura","Lena Roth","Ivo Petrov","Zoe Marin","Ben Ashford"],
    hits: [
      { name: "James Whitfield", why: "mid-market fund in Mayfair" },
      { name: "Amara Okafor", why: "ex-Permira" },
      { name: "Daniel Levy", why: "closed a secondaries fund in May" },
    ],
  },
  daily: { title: "One message a day." },
  join: { title: "Get on the list." },
  footer: { email: "hello@getmutuals.ai", links: [{ label: "Privacy", href: "/privacy" }, { label: "Imprint", href: "/imprint" }] },
} as const;
